version: '3.2'

services:
  zookeeper:
    image: 'bitnami/zookeeper'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-bridge
      - kafka-overlay
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  
  zookeeper-navigator:
    image: 'elkozmon/zoonavigator'
    ports: 
      - '9090:9090'
    environment:
      - HTTP_PORT=9090
    depends_on:
      - zookeeper
    networks:
      - kafka-bridge
      - kafka-overlay
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  kafka:
    image: 'bitnami/kafka'
    volumes:
      - 'kafka_data:/bitnami'
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
    depends_on:
      - zookeeper
    networks:
      - kafka-bridge
      - kafka-overlay
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  
  kafdrop:
    image: 'obsidiandynamics/kafdrop'
    ports: 
      - '9094:9094'
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - SERVER_PORT=9094
    depends_on:
      - kafka
    networks:
      - kafka-bridge
      - kafka-overlay
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  kafka-bridge:
    external:
      name: bridge
  kafka-overlay:
    driver: overlay
    attachable: true
